sudo: false
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
licenses:
    - "android-sdk-license-.+"
    - ".+"
before_install:
  - yes | sdkmanager "platforms;android-28"
  - gradle -b wrapper.gradle wrapper
script:
  - ./gradlew clean test
env:
  - secure: DaCjlQj6qmVs9INLDRtysVckmeyURplWGKjhaX2ZrjdtgBc3O2e5pfUCw8yR+tW4MPUKT2eDws/G2oEBnFPO/JIqGznSb8tpAWm8y1ZKXoeDAP+w8kqaUe5MIv98XGdPDMDff2jHO/z6DzwC4ALZUvT2TmdVorJtBncwtPqm9tYrH9w99cTN9blqdQilpeDLHxK+1W61WXwj5LtzhoXtoLsHWHLjU9QxBJV0w5OUD0DfW84AICqGa4h1Vj2gweotLJP2ZiGWqDI3IceSe0b9pPXEQQP0LMI1N1uhmuzT0SAoA2BlMT7h767S/EGROwwRV8kO6bN6OpuGtuDUsaGIvIyNbkCO5rLV9sM/kd8HXo6IwsPou4xayP3pTnjbwgZK67HKPQRiLGupa6j9UNhqpnzIRS2imuAAk2ekuVB44EVEcxtohZu7wgWMNNq23sZjMjZi0rPtIJCK/JD5/CgTUbV1J3wZBLXiIKxPmDsitE69+S9fADM1GdVqrMZuUsV36UknGg35e2UbNSHk08hkBR+diDyMd8wTgZCcYwrNDyrLDIFkVbwVCIb5MuNZOGcRWys9fb3HxydsF5wczKEET8fHZc7iz4Ct5aJwEYtUyw599jdlvgQdzp4BNCWEnlxzydHUT/7kl3LImweRvQqd2hkZ/uR7WurZd//HG9tYxxE=
deploy:
  provider: script
  script: ./gradlew clean bintrayUpload
  on:
    tags: true
