name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: gradle -b bootstrap.gradle wrapperBuild
      - run: ./gradlew clean test
