name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew clean test
